### PR TITLE
Some updates and cleanup

### PR DESCRIPTION
**Pull request by MichaelMay81**
- Updated some stuff to Python 3
- Revised the interpolation code
- Type annotations
- A bit of documentation

I needed Kochanek Bartels spline for a project and your stuff saved me from implementing it from scratch, Thanks!! Maybe my changes are helpful for you too...
:) m

### CODE REVIEW

**Comment by chozabu** [comment]
Looks good! Glad it helped - though I cant really take much credit - I think I only did small changes on top of Geometrians (Ian Malletts) work.

Curious to know what your project is if you are able to share?

**Comment by MichaelMay81** [comment]
Couldn't talk much about the project back than, but now it is long done. We were generating 3d scenes from OpenStreetMap geodata.
https://www.vrvis.at/en/research/research-projects/former-projects/kaust-scene-generator

**Comment by chozabu** [comment]
@MichaelMay81 Interesting stuff! Is kaust-scene-generator something I can download and try out locally?

**Comment by MichaelMay81** [comment]
It is not publicly available as far as I know.
We wrote python scripts in combination with Blender to create the geometry.

**Pull request merged**
